# Generated by Django 4.2.1 on 2023-07-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachements',
            new_name='attachments',
        ),
    ]
