# Generated by Django 4.2.1 on 2023-06-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_connect_with_friendshiprequest_connect_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='connect_for',
            new_name='connect_with',
        ),
    ]
